
*  Use musical sounds to represent complex structures
** Replacement 'vision' for blind people.
** Control of complex interfaces when vision is already busy with something else.
*** Communicate important parameters (key readings, radar picture) to a  driver or a pilot.
** Human hearing is nuanced, and humans are good at recognizing patterns in audio signals.
** Humans are good at processing visual and aural information simultaneously,

* How
** By pitch
*** Sound's pitch represent parameter values.
*** Different parameters can be represented as a continuous tone (only 1-2 most important, optionally) or as periodic bursts (usually).
*** Smooth variation in pitch can imitate the Doppler effect and give the sense of both relative speed and position to a sound. This should be applied to entire chords when chords are used.
*** Short noise-like sounds (clicks, blasts, etc) that don't have easily recognizable pitch variation can be used at constant pitch.
** By timing
*** Repetition periods and duration, and also attack / sustain / fade characteristics, represent related parameter values. Different durations may result in interestingly changing texture of chords.
*** Related sounds are grouped together in time to build chords. E.g. in navigation sounds representing various parts / parameters of a complex object should be grouped.
*** Short echo can be represented as an accent (a boolean parameter).
** By voice
*** Different timbres mark different parameters.
*** When a pitch range of a sound is known to be significantly limited (e.g. only 1-2 octaves), the same timbre (e.g. same sample) can be reused for different parameters at very different pitches.
*** The set of samples / instruments / etc should only include sounds that are easy to tell apart in the whole pitch range.
*** Only certain smooth and predictable timbre variations are good for representing continuous values of small ranges. FM-synthesized signals are probably good at this. 
*** Entire chords can change their frequency envelope in concert (low-pass / high-pass) to represent changes in the whole group of related signals, e.g. height or angle during navigation, getting within a critical distance, etc.. 
** By volume
*** Volume represents relative significance of signals, e.g. distance from the user while navigating.
*** Constant 'baseline' signals can be made low-voulme to give room to quickly changing signals.
** By spatial cues
*** Stereo separation gives a basic idea of parameter's 'heading'. This makes specific sense for space orientation, but may also be used to represent several (2-4) similar 'channels' for non-spatial values.
*** Spatial processing may add a 'fore-back' axis, giving an additional 360° directional dimension to the sound. This is especially important for vision-replacing applications.

* Problems
** Chords and progressions, as they build, may draw emotionally-colored pictures, Fine for 3D navigation, poor for pilot's parameter reading. A "neutralizing" tone scale, e.g. pentatonic, could alleviate this.
