# Personal Cloud

* Common in-cloud services for parts
  ; This what an OS should be providing.
  ; As thin a layer above the OS as possible.
  ; As language-agnostic as possible.
  ; See App Engine.

** Security.
*** Authentication service.
**** OpenID, OAuth accepted from remote systems
**** (?) OpenID, OAuth provided outside
**** Gravatar for userpics.
**** A local profile can be filled in to give more details.
**** Internally may link profiles to contacts.
*** Capability-based access control.
*** Encryption service (uses user's secrets).
**** (?) SSH infrastructure exposed
**** (?) GPG keys and infrastructure exposed

** Storage
*** Persistent blob storage (binary data), mime-typed.
**** Efficient search by keys and by tags.
*** Tagging service
**** Tag discovery for items that reasonably support it
     ; audio, photo.
**** Unique [sub]tags are automatically added to each data item.
**** Tag-based "file system".
*** (?) Full-text search
*** Memcached
*** (?) RDBMS
*** (?) Fast key-value DB

** Internal messaging
*** Queues
*** Cron
*** (?) pub-sub
    ; Has issues.

** Contacts
*** Profiles for human contacts
    ; linked to security credentials if needed
*** (?) Profiles for machine accounts
    ; external services, RSS feeds, etc

* User-facing apps
  ; Built on top of common services.

** File storage.
   ; Exposes the tag-based "file system"
** Picture gallery.
** Video gallery.

** Webmail.
   ; a web interface on top of regular exim/dovecot or whatnot.
** Contacts / address book management
** Calendar.
   ; if possible, on top of a regular calendar server.

** Word processor
   ; See hackpad and ginkgo-app
*** Must have serious offline capabilities

** Spreadsheet?
*** Must have serious offline capabilities


* Extensibility
  ; Common language-neutral engine allows to add parts.
  ; Language-neutral late binding: HTTP, REST, JSON.

* Publishing
  ; Any piece may provide consumer views, intended not only for authors / owners.

** Authenticated consumer access

** Public / anonymous access
   ; OK for viewing.  With caution, possible for commenting.

** Comments
*** Easy to integrate into consumer views.
*** Use auth.
*** Tree or flat.

* Navigation

** Tags
   ; See the reverse tags document
*** Tags are hierarchical
    ; most specific part goes first: inbox/mail, "Moby Dick"/title
    ; Assume slash to separate level, double quotes to quote spaces.
*** Tags are pervasive.
    ; All applications within the cloud use the same set of tags.
*** Tags have presentation attributes
    ; color, a short text blurb, maybe an icon, set manually or
    ; auto-extracted form auto-tags, like userpic for contacrs.
*** Contacts serve as implicit tags
    ; Probably "firsname lastname"/contact and nickname/contact

** Saved searches, aka Folders
   ; Searches by any content can be saved. Possibly "sub-searches" with additional
   ; constraints can look like "sub-folders".

   ; Searches purely by tags are *drag targets*: if any taggable item was dragged 
   ; onto them, necessary tags are added, incompatible tags are removed. 
   ; It's a fast categorization tool.

* Concurrent updates and consistency

* Version control

* Implementation

Message bus / queues.
Key-value blob store with byte-range access.
Full-text indexing engine.
Tag storage.
Common internal REST-like interfaces.
Language independence.

** Authentication

*** Author Authentication 
*** Facets

** Consumer authentication
*** OpenID
*** OAuth
*** Linking of accounts (or not)

** Anonymous aka public access

** Service Description and Discovery Common message bus

** Abstracted and custom storage


